more rustflags opts
Alex313031/Mercury pull request #168
Opened 2024-03-28 21:49 UTC by SashaXser

Added the tune-cpu option as well as target-cpu for macos-arm64. I'll leave it as a draft for now

2024-04-04 04:58 UTC, gz83 commented
Have you done any performance comparison testing? Sometimes adding too many optimization parameters can be counterproductive.

In addition, some of the parameters you added may not be appropriate, and there are also wrong parameters.

2024-04-04 04:59 UTC, gz83 requested changes

2024-04-04 04:59 UTC, gz83 commented on mozconfigs/mozconfig
> +export CPPFLAGS="-O3 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mae -mtune=sandybridges"
Nit: -mae?

2024-04-04 06:53 UTC, SashaXser commented
> Have you done any performance comparison testing? Sometimes adding too many optimization parameters can be counterproductive.
> 
> In addition, some of the parameters you added may not be appropriate, and there are also wrong parameters.

I can't run the tests right now, can you run the tests for me?

2024-04-04 07:21 UTC, gz83 commented
Sorry, I don't have any resources right now to test the performance differences

2024-04-06 13:00 UTC, SashaXser commented
If you don't like it, close it. I don't want to do anything else.

2024-04-14 10:25 UTC, closed without merging