Change executable name to avoid CPU bug
Alex313031/Mercury pull request #196
Opened 2024-06-18 05:05 UTC by wagesj45

To avoid the high CPU bug observed in #185, the branding in the mozconfig files has been changed to `mercurybrowser` instead of `mercury`. The rest of the branding should remain intact, but the `exe` file will be named `mercurybrowser.exe` instead of `mercury.exe`, which was conflicting with the Gotham Knights application profile with Nvidia.

2024-07-01 13:23 UTC, TanvirOnGH approved these changes

2024-07-01 14:03 UTC, gz83 requested changes
-1

2024-07-01 14:03 UTC, closed without merging

2024-07-01 17:13 UTC, wagesj45 commented
Is there a different fix for this bug in the works?

2024-07-02 05:03 UTC, gz83 commented
The changes in this CL do not seem to be completely correct. In addition, please communicate with Alex before making any changes.

In the meantime, the PR has been approved by someone who is not a member or collaborator of the repository, so I will temporarily give it a -1.

@Alex313031